### ISSUE TITLE
MetaMask Snaps Bounty + EthWaterloo-2019

### ISSUE THREAD

**Issue by JSON-LEE13** [MetaMask/Hackathons#1]
### **Best Working MetaMask Snaps plugin**

**Bounty:**
1st place 1,500 DAI
2nd place 500 DAI
 
**Description**
Come and try out an early version of a new kind of MetaMask; one that allows the decentralized web to innovate faster than ever, while improving user experience, without compromising security.
Each MetaMask Snap created has the ability to provide its own API to the sites that a user visits, as well as to other plugins. This allows plugins to build on each other, forming a sort of decentralized dependency graph. We expect this to rocket-propel the pace of innovation leading to countless possibilities, but here are a few things Snaps can enable:

- New asset types (tokens, subscriptions, credit lines, CDPS, etc)
- New protocol support (ipfs, ssb, dat, gundb)
- New Layer 2 solution integrations
- New account types (remote signers, contract accounts)

For this challenge, our team would like to harness the ETHWaterloo community’s creativity for the best Snap they can make.

**General Plugin Guidelines and questions to consider** 

1. Who is this snap for? Who is the user - and why would they care about using this snap?
2. What is the user problem you are solving with this snap?
3. Which technologies would you use? 
4. What are the minimal permissions you need from users to run the snap?
5. What kind of UI does your snap need? 
   a.   Can your snap’s UI be handled by dapps or do you need to interact with MetaMask’s UI?
      i.   If the latter, do you need your own iframe or would hooks provided by MetaMask suffice?
   b.   What does the user flow look like after snap integration with MetaMask?
      i.   Is it usable / intuitive to use? 
   c.   How does a user get onboarded to this snap? In which context (e.g., does a dapp recommend 
         it? Do you expect users to install from a snap list / store?)  

Note: Snaps that are created as parts of other projects or larger systems are still eligible for this bounty. For example, if you create a snap to support a dapp you are building, that snap is eligible for entry.

**Submission Requirements** 
1. A brief write-up listing the benefits of this snap and its target users
2. A functioning snap that has been integrated with MetaMask
3. (Optional) Any supporting artifacts that complements the implemented snap like user flow diagrams, use-case that you expect people to use it, steps for making this snap production ready etc.

**Submission Deadline**
November 10th, 2019, per the ETHWaterloo Guidelines. 
 
**Judging Criteria**
-We’re looking for snaps that extend the functionality of the wallet in powerful ways:
-Making new kinds of dapps possible
-Integrating scaling solutions
-Granting new features to the user’s account
-Increasing privacy for dapp users
-Empowering people to do things they can’t do with traditional money

We’re looking for snaps that integrate with MetaMask in a user-friendly manner:
-Contextual user onboarding
-A consistent UI of snap with MetaMask

**Resources**
[An intro video](https://www.youtube.com/watch?v=VkvElJY6uLs&feature=youtu.be)
[MetaMask Plugin Beta Wiki!](https://github.com/MetaMask/metamask-plugin-beta/wiki)
[Fork of MetaMask that supports plugins!](https://github.com/MetaMask/metamask-plugin-beta)
[Plugin API](https://github.com/MetaMask/metamask-plugin-beta/wiki/Plugin-API)
[Join our MetaMask ETHwaterloo Discord Channel ](https://discord.gg/jXqcACD)
[Join our Team on Keybase "MetaMask_Plugins" for general comms ](https://keybase.io/team/metamask_plugins)

**Judging Date**
November 10th, 2019, per the ETHWaterloo Guidelines.

**Comment by rpavlovs** [comment]
We’re making a wallet notification service and thinking of forking MetaMask for that, but making a plug-in sounds much better. 

Can we meet up and talk? 
My discord handle is `rpavlovs`

**Comment by JSON-LEE13** [comment]
**The Winners Of Our Bounty**

1st Place (1500 Dai)
https://devpost.com/software/dc-wallet

2nd Place (500 Dai) 
https://devpost.com/software/connexion-vy3a9c#updates
